import type { Metadata } from "next";
// import { Spartan, Silk_Serif, Shalimar } from "next/font/google";
import { League_Spartan, Shalimar, Lora } from "next/font/google";

import "./globals.scss";
import LayoutSite from "@/components/layout/LayoutSite";

const spartan = League_Spartan({
  variable: "--font-spartan",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const shalimar = Shalimar({
  variable: "--font-shalimar",
  subsets: ["latin"],
  weight: "400",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spartan.variable} ${lora.variable} ${shalimar.variable} antialiased`}
      >
        <LayoutSite>
          {children}
        </LayoutSite>
      </body>
    </html>
  );
}
